
//import com.nilo.plaf.nimrod.NimRODLookAndFeel;
//import com.nilo.plaf.nimrod.NimRODTheme;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import java.io.*;
import java.text.ParseException;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.UnsupportedLookAndFeelException;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nidhi
 */
public class NewJFrame extends javax.swing.JFrame {
String age1,cpt1,chol1,fbs1,rate1,eia1,oldpeak1,slope1,color1,thal1,ecg1,str;
String gender1,restbp1;
public String getSelectedButtonText(ButtonGroup buttonGroup) {
    for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
        AbstractButton button = buttons.nextElement();
        if (button.isSelected()) {
            return button.getName();
        }
    }
    return null;
}

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        male = new javax.swing.JRadioButton();
        ageLabel = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        genderLabel = new javax.swing.JLabel();
        cptLabel = new javax.swing.JLabel();
        cpt = new javax.swing.JComboBox();
        restbpLabel = new javax.swing.JLabel();
        restbp = new javax.swing.JTextField();
        cholLabel = new javax.swing.JLabel();
        chol = new javax.swing.JTextField();
        fbsLabel = new javax.swing.JLabel();
        fbs = new javax.swing.JTextField();
        mhrLabel = new javax.swing.JLabel();
        mhr = new javax.swing.JTextField();
        eiaLabel = new javax.swing.JLabel();
        eiaTrue = new javax.swing.JRadioButton();
        eiaFalse = new javax.swing.JRadioButton();
        oldpeakLabel = new javax.swing.JLabel();
        oldpeak = new javax.swing.JTextField();
        slopeLabel = new javax.swing.JLabel();
        slope = new javax.swing.JComboBox();
        colorLabel = new javax.swing.JLabel();
        color = new javax.swing.JSpinner();
        thalLabel = new javax.swing.JLabel();
        thal = new javax.swing.JComboBox();
        ecgLabel = new javax.swing.JLabel();
        ecg = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        predict = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        age = new javax.swing.JSpinner();
        nameLabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HeartCare+");
        setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture1_2.png"))); // NOI18N
        title.setToolTipText("");
        title.setOpaque(true);

        buttonGroup1.add(male);
        male.setText("Male");
        male.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        male.setName("1"); // NOI18N
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        ageLabel.setText("Age:");

        buttonGroup1.add(female);
        female.setText("Female");
        female.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        female.setName("0"); // NOI18N
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        genderLabel.setText("Gender:");

        cptLabel.setText("Chest Pain Type:");

        cpt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not sure", "Typical Angina", "Atypical Angina", "Non-angina Pain", "Asymptomatic" }));
        cpt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cpt.setPreferredSize(new java.awt.Dimension(66, 20));
        cpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cptActionPerformed(evt);
            }
        });

        restbpLabel.setText("Resting Blood Pressure:");

        restbp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        cholLabel.setText("Cholesterol:");

        fbsLabel.setText("Fasting Blood Sugar(<120):");

        fbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbsActionPerformed(evt);
            }
        });

        mhrLabel.setText("Maximum Heart Rate:");

        eiaLabel.setText("Exercise Induced angina:");

        buttonGroup2.add(eiaTrue);
        eiaTrue.setText("True");
        eiaTrue.setName("1"); // NOI18N
        eiaTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eiaTrueActionPerformed(evt);
            }
        });

        buttonGroup2.add(eiaFalse);
        eiaFalse.setText("False");
        eiaFalse.setName("0"); // NOI18N
        eiaFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eiaFalseActionPerformed(evt);
            }
        });

        oldpeakLabel.setText("Old Peak:");

        oldpeak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpeakActionPerformed(evt);
            }
        });

        slopeLabel.setText("Slope:");

        slope.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not sure", "Up", "Flat", "Down" }));
        slope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slopeActionPerformed(evt);
            }
        });

        colorLabel.setText("Number of Vessels Colored:");

        color.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3, 1));
        color.setEditor(new javax.swing.JSpinner.NumberEditor(color, ""));

        thalLabel.setText("Thal:");

        thal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not sure", "Normal", "Fixed defect", "Reversible defect" }));

        ecgLabel.setText("Resting ECG:");

        ecg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not sure", "Normal", "Abnormality", "Hypertrophy" }));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Please enter the details below:");
       predict.setText("Predict");
        predict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt){
				try{ 
                predictActionPerformed(evt);
				}catch(Exception e){
	System.out.println(e);
}
            }
        });


        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        age.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        nameLabel.setText("Name:");

        name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        output.setEditable(false);
        output.setColumns(20);
        output.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        output.setLineWrap(true);
        output.setRows(5);
        output.setWrapStyleWord(true);
        output.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fbsLabel)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cholLabel)
                            .addComponent(ageLabel)
                            .addComponent(restbpLabel)
                            .addComponent(genderLabel)
                            .addComponent(nameLabel)
                            .addComponent(cptLabel))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(male, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addGap(58, 58, 58))
                            .addComponent(female, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(age, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                        .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(cpt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(restbp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chol, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fbs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldpeakLabel)
                            .addComponent(mhrLabel)
                            .addComponent(eiaLabel)
                            .addComponent(slopeLabel))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldpeak, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mhr, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ecgLabel)
                            .addComponent(thalLabel)
                            .addComponent(colorLabel))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ecg, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slope, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eiaTrue)
                            .addComponent(eiaFalse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(predict, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameLabel)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mhrLabel)
                                    .addComponent(mhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(genderLabel)
                                            .addComponent(male)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ageLabel)
                                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(female)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cptLabel)
                                    .addComponent(cpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(restbpLabel)
                                    .addComponent(restbp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cholLabel)
                                    .addComponent(chol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fbsLabel)
                                    .addComponent(fbs)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eiaLabel)
                                    .addComponent(eiaTrue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eiaFalse)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(slopeLabel)
                                    .addComponent(slope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(colorLabel)
                                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(thalLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(thal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ecg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ecgLabel))))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(oldpeak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(oldpeakLabel)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(predict, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addComponent(jSeparator3)))))
        );

        male.getAccessibleContext().setAccessibleName("1");
        female.getAccessibleContext().setAccessibleName("0");
        eiaTrue.getAccessibleContext().setAccessibleName("1");
        eiaFalse.getAccessibleContext().setAccessibleName("0");

        pack();
    }// </editor-fold>                        

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void fbsActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void eiaFalseActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void eiaTrueActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void oldpeakActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void predictActionPerformed(java.awt.event.ActionEvent evt)throws IOException {                                        
        
        try {
            try {
                age.commitEdit();
            } catch (ParseException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            int ag=(int)age.getValue();
            age1=Integer.toString(ag);
            
            gender1=getSelectedButtonText(buttonGroup1);
            try{
                if(gender1.equals(""))
                    gender1="?";
            }
            catch(Exception e){
                gender1="?";
            }
            cpt1=Integer.toString(cpt.getSelectedIndex());
            if(cpt1.equals("0"))
                cpt1="?";
            
            restbp1=restbp.getText();
            try{
                if(restbp1.equals(""))
                    restbp1="?";
            }
            catch(Exception e){
                restbp1="?";
            }
            
            chol1=chol.getText();
           try{ if(chol1.equals(""))
                chol1="?";}
            catch(Exception e){
                chol1="?";
            }
            fbs1=fbs.getText();
             try{
                 if(fbs1.equals(""))
                    fbs1="?";
                 }
            catch(Exception e){
                fbs1="?";
            }
             
            ecg1=Integer.toString(ecg.getSelectedIndex());
            try{
                if(ecg1.equals("0"))
                    ecg1="?";
            }
            catch(Exception e){
                ecg1="?";
            }
            
            rate1=mhr.getText();
              try{ if(rate1.equals(""))
                rate1="?";
              }
             catch(Exception e){
                rate1="?";
            }  
            eia1=getSelectedButtonText(buttonGroup2);
           try{ if(eia1.equals(""))
                eia1="?";
               }
            catch(Exception e){
                eia1="?";
            }
            oldpeak1=oldpeak.getText();
            try{if(oldpeak1.equals(""))
                oldpeak1="?";
            }
             catch(Exception e){
                oldpeak1="?";
            }
            slope1=Integer.toString(slope.getSelectedIndex());
              try{if(slope1.equals("0"))
                slope1="?";
                  }
               catch(Exception e){
                slope1="?";
            }
            try {
                color.commitEdit();
            } catch (ParseException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            int co=(int)color.getValue();
            Integer.toString(ag);
            color1=Integer.toString(co);
            int th=thal.getSelectedIndex();
            switch(th){
                case 1:
                    thal1="3";break;
                case 2:
                    thal1="6";break;
                case 3: 
                    thal1="7";break;
                case 0:
                    thal1="?";
            }
            
       // PrintWriter pw = new PrintWriter(new FileWriter("input.txt"));
        str=age1+","+gender1+","+cpt1+","+restbp1+","+chol1+","+fbs1+","+ecg1+","+rate1+","+eia1+","+oldpeak1+","+slope1+","+color1+","+thal1+",?";
        //pw.println(age1+","+gender1+","+cpt1+","+restbp1+","+chol1+","+fbs1+","+rate1+","+eia1+","+oldpeak1+","+slope1+","+color1+","+thal1+","+ecg1);
        //pw.flush();
        //pw.close();
        if(str.contains("")){
            PrintWriter output1 = new PrintWriter(new FileWriter("SwissData.txt", true));
            output1.println();
            output1.append(str);
            output1.flush();
        }
        else
        {
            PrintWriter output2 = new PrintWriter(new FileWriter("input.txt"));
            output2.println(str);
            //output2.append(str); 
            output2.flush();
        }
         String command1[]={"LikeABoss.bat"};
          ProcessBuilder pb1=new ProcessBuilder(command1);
		   pb1.redirectErrorStream(true);
           pb1.directory(new File("."));
            Process process1 = pb1.start();
            BufferedReader reader = new BufferedReader(new InputStreamReader(process1.getInputStream()));
StringBuilder builder = new StringBuilder();
String line = null;
System.out.println("1");
while ( (line = reader.readLine()) != null) {
  builder.append(line);
  builder.append(System.getProperty("line.separator"));
}
//String result = builder.toString();


            System.out.println("2");
try {
	 System.out.println("\n\nExit Value is hhjghjghj");
	 
            int exitValue = process1.waitFor();
					
					
					
                System.out.println("\n\nExit Value is " + exitValue);
            } 
            catch (InterruptedException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        
        
    }
    catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
    }

    BufferedReader br1 =new BufferedReader(new InputStreamReader(new FileInputStream("output.txt")));
    String line=br1.readLine();
    System.out.println("hellooooooo");
    
    if(line.equals("yes")){
        output.append("You have high chances of having a heart disease");
       // str=str+"0";
    }
    else{
        output.append("You have low chances of having a heart disease"); 
      //  str=str+"1";
    }
        
    
        
    }                                       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        age.setValue(0);
        buttonGroup1.clearSelection();
        cpt.setSelectedItem("Not sure");
        restbp.setText("");
        chol.setText("");
        fbs.setText("");
        mhr.setText("");
        buttonGroup2.clearSelection();
        oldpeak.setText("");
        slope.setSelectedItem("Not sure");
        color.setValue(0);
        thal.setSelectedItem("Not sure");
        ecg.setSelectedItem("Not sure");
        output.setText("");
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void slopeActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void cptActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws IOException, UnsupportedLookAndFeelException {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
//        /* Set the Nimbus look and feel */
//   NimRODTheme nt = new NimRODTheme( "D://Downloads//greenwhite.theme");
//
//NimRODLookAndFeel nf = new NimRODLookAndFeel();
//NimRODLookAndFeel.setCurrentTheme( nt);
//UIManager.setLookAndFeel(nf);
////<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//       /* try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewJFrame().setVisible(true);
//            }
//        });
      /*  try {
    for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
            UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (Exception e) {
    // If Nimbus is not available, you can set the GUI to another look and feel.
}*/
     /*   try {
            // select Look and Feel
            //UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            // start application
             com.jtattoo.plaf.acryl.AcrylLookAndFeel.setTheme("Green", "INSERT YOUR LICENSE KEY HERE", "my company");
            
            // select the Look and Feel
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });*/
    /*  try {
    for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
            UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (Exception e) {
    // If Nimbus is not available, you can set the GUI to another look and feel.
    System.out.println("error");
}
       */
  /*      try {
    UIManager.setLookAndFeel("com.seaglasslookandfeel.SeaGlassLookAndFeel");
} catch (Exception e) {
    e.printStackTrace();
}
  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
      */
    }

    // Variables declaration - do not modify                     
    private javax.swing.JSpinner age;
    private javax.swing.JLabel ageLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField chol;
    private javax.swing.JLabel cholLabel;
    private javax.swing.JSpinner color;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JComboBox cpt;
    private javax.swing.JLabel cptLabel;
    private javax.swing.JComboBox ecg;
    private javax.swing.JLabel ecgLabel;
    private javax.swing.JRadioButton eiaFalse;
    private javax.swing.JLabel eiaLabel;
    private javax.swing.JRadioButton eiaTrue;
    private javax.swing.JTextField fbs;
    private javax.swing.JLabel fbsLabel;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mhr;
    private javax.swing.JLabel mhrLabel;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField oldpeak;
    private javax.swing.JLabel oldpeakLabel;
    private javax.swing.JTextArea output;
    private javax.swing.JButton predict;
    private javax.swing.JTextField restbp;
    private javax.swing.JLabel restbpLabel;
    private javax.swing.JComboBox slope;
    private javax.swing.JLabel slopeLabel;
    private javax.swing.JComboBox thal;
    private javax.swing.JLabel thalLabel;
            
    private javax.swing.JLabel title;
    // End of variables declaration                   
}
